- display_blocks.js
- webserver.py
This fixes:
* https://github.com/ISISComputingGroup/IBEX/issues/1674
* https://github.com/ISISComputingGroup/IBEX/issues/1675
To test:
* Run JSON bourne on your machine
* Modify the get blocks js to point to localhost
* Confirm that you can get the NDXDEMO info from inst_status.html?Instrument=NDXDEMO
This has been tested on other machines for stability and stress
> Tickets 1674+1675 move json bourne and cache it

- block.py
- display_blocks.js
- get_webpage.py
- inst_status.html
https://github.com/ISISComputingGroup/IBEX/issues/1505
> Ticket1505 toggle hidden blocks

- display_blocks.js
To test:
* Open the webpage locally e.g. open default.html?Instrument=larmor
* Confirm the data is refreshed after ~5 seconds
Once tested:
* Deploy on extaweb by replacing the javascript in the IbexDataweb folder
> Added a periodic refresh to the page

- get_webpage.py
- webserver.py
Fixed https://github.com/ISISComputingGroup/IBEX/issues/1991
Already deployed and therefore fixed https://github.com/ISISComputingGroup/IBEX/issues/1988
> Fixed bug where PVs with no value were crashing webdashboard

- block.py
- get_webpage.py
Fixes https://github.com/ISISComputingGroup/IBEX/issues/2144
To test:
* Point the web dashboard at an instrument where the runtime pv is disconnected (zoom at the moment)
* Confirm that the webpage is still shown but the runtime appears disconnected
> Ticket2144: Added check on time conversion for the pv being disconnected

- webserver.py
See https://github.com/ISISComputingGroup/IBEX/issues/2295
To test:
* Start the webserver locally https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard#developmenttesting
* Confirm that you can connect to your web dashboard
* Stop your instrument (you cant use stop_inst as it will also kill the webserver, instead console into the BS and stop that)
* Confirm that your webdashboard now shows an error
* Restart your instrument
* Confirm that you can connect to your web dashboard
> Ticket2295: Return an error when data cannot be scraped

- display_blocks.js
Fixes https://github.com/ISISComputingGroup/IBEX/issues/2263
To test:
* Set up dev machine: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard#developmenttesting
* Point at your instrument and confirm that the run info is in the same order as in seci, e.g:
> Ticket 2263: Fix order of run info

- default.html
- display_blocks.js
https://github.com/ISISComputingGroup/IBEX/issues/2159
> Ticket2159: Fixed strict HTML errors

- default.html
See https://github.com/ISISComputingGroup/IBEX/issues/2734
To test:
* Load up web dashboard
* Confirm the report a bug link is visible both when you are pointing to a valid instrument and when you are not
> Ticket 2734: Added bug report button to web dashboard

- block_utils.py
- display_blocks.js
- external_webpage/instrument_information_collator.py
- webserver.py
See https://github.com/ISISComputingGroup/IBEX/issues/2769
To test:
* See https://github.com/ISISComputingGroup/EPICS-ioc/pull/207
> Ticket2663: Added shutter status to web page

- display_blocks.js
- external_webpage/instrument_information_collator.py
Add DAE simulation mode to dataweb.
https://github.com/ISISComputingGroup/IBEX/issues/2659
> Add DAE simulation mode to dataweb

- default.html
- display_blocks.js
- external_webpage/instrument_information_collator.py
Fixes https://github.com/ISISComputingGroup/IBEX/issues/2694
Requires new archive engine build on each instrument. 
**Acceptance Criteria**
> Ticket2694 web dashboard style issues

- external_webpage/request_handler_utils.py
- tests/test_handler_utils.py
- webserver.py
See https://github.com/ISISComputingGroup/IBEX/issues/2929
To test:
* Run unit tests, confirm they cover the changes and now pass
* Connect to a locally run instance of JSON bourne, pointing to EMMA-A
> Ticket 2929: JSON Bourne can now connect to EMMA-A

- block.py
- block_utils.py
- display_blocks.js
- external_webpage/web_page_parser.py
- tests/data_mother.py
- tests/test_block_utils.py
- webserver.py
Formats numbers in scientific notation for https://github.com/ISISComputingGroup/IBEX/issues/2069
> Ticket2069

- front_end/display_blocks.js
https://github.com/ISISComputingGroup/IBEX/issues/4703
> Make alarm text a hyperlink to documentation

- block_utils.py
- external_webpage/instrument_information_collator.py
- front_end/display_blocks.js
New PVs for labels and values are read and displayed on Dashboard correctly.
**Ticket**
[#5074](https://github.com/ISISComputingGroup/IBEX/issues/5074)
**Acceptance criteria**
> Made changes to display labels on Dashboard using PVs

- start_websever.bat
> Add script

- requirements.txt
- start_websever.bat
Added a requirements file to aid in deployment in the future. Tangentially related to https://github.com/ISISComputingGroup/IBEX/issues/4036.
To test:
* Create a clean virtual environment: `python -m venv my_virtual_env`
* Start virtual environment `my_virtual_env\Scripts\activate.bat`
* Confirm that the JSON_bourne tests fail: `python run_tests.py`
* Install the requirements `pip install -r requirements.txt`
* Confirm tests now pass and JSON bourne works as intended (see https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard#developmenttesting)
> Ticket 4036: Update JSON bourne

- external_webpage/data_source_reader.py
- webserver.py
> Time out on URL get

- front_end/display_blocks.js
Add link to Grafana graph, to see the graph requires a successful federal id or user office login 
See ISISComputingGroup/IBEX#5504 and  ISISComputingGroup/IBEX#5669
> Link to grafana graph

- front_end/display_blocks.js
Fix syntax for parsing with phantomjs (slack)
> Fix error when parsed with phantomjs on slack

- front_end/display_blocks.js
Fix grafana links with hyphens in instrument name
> Fix parse part2

- block_utils.py
- external_webpage/data_source_reader.py
- external_webpage/instrument_information_collator.py
- external_webpage/instrument_scapper.py
- external_webpage/utils.py
- external_webpage/web_scrapper_manager.py
- tests/test_data_source_reader.py
- tests/test_get_info_from_config_and_web.py
- tests/test_inst_list.py
- tests/test_web_scrapper_manager.py
See https://github.com/ISISComputingGroup/IBEX/issues/6511
To test:
* Run JSON Bourne locally and confirm it shows data for POLREF and HRPD
* Confirm unit tests still pass
> Ticket 6511: Try to get config information from channel access first

- external_webpage/instrument_information_collator.py
- front_end/default.html
- front_end/display_blocks.js
Make json bourne more relaiable by adding default option for getting from inst_details json.
https://github.com/ISISComputingGroup/IBEX/issues/6464
> Add default option for getting from inst_details

- front_end/Overview/ibexOverview.html
- front_end/Overview/ibexOverview.js
We should do ISISComputingGroup/IBEX#7011 as a permanent fix - this is just to get us out of trouble for the cycle
To test: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard#developmenttesting
To deploy: https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard#deployment
> Seperate instruments in overview

- front_end/display_blocks.js
> Validate instrument

- front_end/Overview/ibexOverview.js
SXD not on inst list yet, when it is we'll probably be running ibex?
> add motion to misc machines
